/**
 * Dassana Profile Service
 * This API provides profile management capabilities like editing of name etc
 *
 * OpenAPI spec version: 1.0.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErrorInfo } from './errorInfo'

/**
 * this object is used when Dassana encounterd an internal error.
 */
export interface InternalError extends ErrorInfo {
	/**
	 * Request id as provided by the client. Please provide this id when you contact the Dassana Support.
	 */
	requestId?: string
}
