/**
 * Dassana Profile Service
 * This API provides profile management capabilities like editing of name etc
 *
 * OpenAPI spec version: 1.0.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimezoneId } from './timezoneId'

export interface TimezoneV2 {
	id?: TimezoneId
	friendlyName?: string
	utcOffset?: string
}
