/**
 * Preferences API
 * This API is developed for managing Preferences.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ConfigKey } from '../model/configKey';
import { ConfigObject } from '../model/configObject';
import { Feature } from '../model/feature';
import { InternalError } from '../model/internalError';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class UserPreferencesService {

    protected basePath = 'https://preferences.dassana.cloud/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * delete data of the user using feature
     * 
     * @param feature pass feature
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteByFeature(feature: Feature, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteByFeature(feature: Feature, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteByFeature(feature: Feature, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteByFeature(feature: Feature, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (feature === null || feature === undefined) {
            throw new Error('Required parameter feature was null or undefined when calling deleteByFeature.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerToken) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/user/config/${encodeURIComponent(String(feature))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * delete data of the user using feature and configKey
     * 
     * @param feature pass feature
     * @param configKey pass configKey
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteByFeatureAndKey(feature: Feature, configKey: ConfigKey, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteByFeatureAndKey(feature: Feature, configKey: ConfigKey, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteByFeatureAndKey(feature: Feature, configKey: ConfigKey, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteByFeatureAndKey(feature: Feature, configKey: ConfigKey, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (feature === null || feature === undefined) {
            throw new Error('Required parameter feature was null or undefined when calling deleteByFeatureAndKey.');
        }

        if (configKey === null || configKey === undefined) {
            throw new Error('Required parameter configKey was null or undefined when calling deleteByFeatureAndKey.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerToken) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/user/config/${encodeURIComponent(String(feature))}/${encodeURIComponent(String(configKey))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get data using feature of the user
     * 
     * @param feature pass feature
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getByFeature(feature: Feature, observe?: 'body', reportProgress?: boolean): Observable<ConfigObject>;
    public getByFeature(feature: Feature, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ConfigObject>>;
    public getByFeature(feature: Feature, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ConfigObject>>;
    public getByFeature(feature: Feature, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (feature === null || feature === undefined) {
            throw new Error('Required parameter feature was null or undefined when calling getByFeature.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerToken) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ConfigObject>('get',`${this.basePath}/user/config/${encodeURIComponent(String(feature))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * fetch data using configKey and feature of the user
     * 
     * @param feature pass feature
     * @param configKey pass configKey
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getByFeatureAndKey(feature: Feature, configKey: ConfigKey, observe?: 'body', reportProgress?: boolean): Observable<ConfigObject>;
    public getByFeatureAndKey(feature: Feature, configKey: ConfigKey, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ConfigObject>>;
    public getByFeatureAndKey(feature: Feature, configKey: ConfigKey, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ConfigObject>>;
    public getByFeatureAndKey(feature: Feature, configKey: ConfigKey, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (feature === null || feature === undefined) {
            throw new Error('Required parameter feature was null or undefined when calling getByFeatureAndKey.');
        }

        if (configKey === null || configKey === undefined) {
            throw new Error('Required parameter configKey was null or undefined when calling getByFeatureAndKey.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerToken) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ConfigObject>('get',`${this.basePath}/user/config/${encodeURIComponent(String(feature))}/${encodeURIComponent(String(configKey))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update data of user using feature and configKey
     * 
     * @param body 
     * @param feature pass feature
     * @param configKey pass configKey
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateByFeatureAndKey(body: { [key: string]: any; }, feature: Feature, configKey: ConfigKey, observe?: 'body', reportProgress?: boolean): Observable<ConfigObject>;
    public updateByFeatureAndKey(body: { [key: string]: any; }, feature: Feature, configKey: ConfigKey, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ConfigObject>>;
    public updateByFeatureAndKey(body: { [key: string]: any; }, feature: Feature, configKey: ConfigKey, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ConfigObject>>;
    public updateByFeatureAndKey(body: { [key: string]: any; }, feature: Feature, configKey: ConfigKey, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateByFeatureAndKey.');
        }

        if (feature === null || feature === undefined) {
            throw new Error('Required parameter feature was null or undefined when calling updateByFeatureAndKey.');
        }

        if (configKey === null || configKey === undefined) {
            throw new Error('Required parameter configKey was null or undefined when calling updateByFeatureAndKey.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerToken) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ConfigObject>('put',`${this.basePath}/user/config/${encodeURIComponent(String(feature))}/${encodeURIComponent(String(configKey))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
