/**
 * Global API References
 * This API doc is meant to host references which can be made from any of the Dassana APIs. This API does not provide any service by itself.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ErrorInfo {
	msg?: string
	key: string
}
