/**
 * Dassana Service Map Service
 * This API provides list of service endpoints for various services for a given user. This service is intended to be used by Dassan
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Service {
	serviceName: string
	apiUrl: string
	webUrl: string
}
