/**
 * Dassana Profile Service
 * This API provides profile management capabilities like editing of name etc
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';


import { InternalError } from '../model/internalError';
import { Persona } from '../model/persona';


import { Configuration }                                     from '../configuration';


export interface PersonaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Returns list of personas
    * 
    */
    listPersonas(extraHttpRequestParams?: any): Observable<Array<Persona>>;

}
