/**
 * Dassana Profile Service
 * This API provides profile management capabilities like editing of name etc
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';


import { BaseProfile } from '../model/baseProfile';
import { ErrorInfo } from '../model/errorInfo';
import { GetProfileV2 } from '../model/getProfileV2';
import { InternalError } from '../model/internalError';
import { Profile } from '../model/profile';
import { UpdateProfileV2 } from '../model/updateProfileV2';


import { Configuration }                                     from '../configuration';


export interface ProfileServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Returns the profile information associated with the currently authenicated entity
    * 
    */
    getProfile(extraHttpRequestParams?: any): Observable<Profile>;

    /**
    * Returns the profile information associated with the currently authenicated entity
    * 
    */
    getProfileV2(extraHttpRequestParams?: any): Observable<GetProfileV2>;

    /**
    * Updates the profile information. Note that either of &#x27;timeZone&#x27; key will be deprecated so please provide timeZoneId
    * 
    * @param id the user id that you want to edit
    * @param body 
    */
    updateProfile(id: string, body?: BaseProfile, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Updates the profile information.
    * 
    * @param id the user id that you want to edit
    * @param body 
    */
    updateProfileV2(id: string, body?: UpdateProfileV2, extraHttpRequestParams?: any): Observable<{}>;

}
