/**
 * Dassana Profile Service
 * This API provides profile management capabilities like editing of name etc
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';


import { InternalError } from '../model/internalError';
import { Timezone } from '../model/timezone';
import { TimezoneV2 } from '../model/timezoneV2';


import { Configuration }                                     from '../configuration';


export interface TimezoneServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Returns list of available time zones
    * 
    */
    getTimeZones(extraHttpRequestParams?: any): Observable<Array<Timezone>>;

    /**
    * Returns list of available time zones
    * 
    */
    getTimezonesV2(extraHttpRequestParams?: any): Observable<Array<TimezoneV2>>;

}
