/**
 * Preferences API
 * This API is developed for managing Preferences.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ConfigObject extends null<String, any> {
	[key: string]: any
}
