/**
 * Preferences API
 * This API is developed for managing Preferences.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * this object is used when Dassana encounterd an internal error.
 */
export interface InternalError {
	/**
	 * Request id as provided by the client. Please provide this id when you contact the Dassana Support.
	 */
	requestId?: string
	msg?: string
	key: string
}
