name: Pull Request on Branch Push

on:
    push:
        branches:
            - 'swaggerhub*'

jobs:
    auto-pull-request:
        name: PullRequestAction
        if: "contains(github.event.head_commit.message, 'SwaggerHub')"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  always-auth: true
                  node-version: '20.x'
                  registry-url: https://npm.pkg.github.com/
                  scope: '@dassana-io'
            - name: Run install and codegen.js
              run: |
                  npm install
                  npm run codegen

                  git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

                  git checkout --track $(git branch -r --sort=-committerdate | grep '\bswaggerhub\b' | head -n 1)

                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@users.noreply.github.com"

                  git add .
                  git commit -m 'Automated swagger codegen'

                  git push
              env:
                  CI: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Open Pull Request
              uses: vsoch/pull-request-action@1.0.6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
                  BRANCH_PREFIX: 'swaggerhub'
                  PULL_REQUEST_BRANCH: 'master'
