name: Node.js CI

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  always-auth: true
                  node-version: '16.x'
                  registry-url: https://npm.pkg.github.com/
                  scope: '@dassana-io'
            - name: Setup timezone
              uses: zcong1993/setup-timezone@master
              with:
                  timezone: America/Los_Angeles
            - name: Run install, lint, test, and build
              run: |
                  npm install
                  npm run lint
                  npm test
                  npm run build
              env:
                  CI: true
