name: Sync Master Branch
on:
    push:
        branches:
            - 'dev'
jobs:
    sync-branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Merge master -> dev
              uses: devmasx/merge-branch@v1.3.0
              with:
                  type: now
                  from_branch: master
                  target_branch: dev
                  github_token: ${{ github.token }}
